### ISSUE TITLE
Unable to turn platinum/mod metals into swords/armors

### ISSUE THREAD

**Issue by Akitori** [Shadows-of-Fire/Foundry#11]
Title says it all. Using the latest foundry and placebo, i cannot make say platinum armor, bronze, etc.

**Comment by Shadows-of-Fire** [comment]
The ability to cast thermal armors is not yet implemented, I need to figure out a good way to access these items dynamically, because they do not have oredict entries.

**Comment by Shadows-of-Fire** [comment]
Fixed in 3.1.1.0
