### ISSUE TITLE
Infinite Metal Dupe capability with Tinkers or similar installed along side Foundry

### ISSUE THREAD

**Issue by Dragnier** [Shadows-of-Fire/Foundry#12]
Metal ingots in this mod melt down to 108 mb. In Tinkers and similar mods that create molten metals, this is typically one ingot melts down to 144 mb. Since you mention Tinkers compatibility in your mod description, I thought you might want to consider matching their value to prevent infinite metal duping.

As it stands, having this mod and Tinkers installed means you can melt ingots in a smeltery for 144 mb, move that to your foundry, cast an ingot for 108 mb, then re-melt that ingot for another 144 in the smeltery. Each pass generates an extra 36 mb per run which equals out to infinite metal duping.

**Comment by Shadows-of-Fire** [comment]
No, it doesnt.  Foundry will not cast TiC fluids at 108 mb to an ingot.
