### ISSUE TITLE
Remove Dependancy on Thermal if possible

### ISSUE THREAD

**Issue by Dragnier** [Shadows-of-Fire/Foundry#13]
I know it's probably easier to depend on another mod for the non-vanilla and molten metals. However, Tinkers only adds modded metals if they are present and therefore doesn't require them to be installed.

If there were some way you could adapt foundry to function in a similar manner so that it could be used with **_any_** ore mod, that would make it much more likely to get used.

**Comment by Shadows-of-Fire** [comment]
This isn't going to happen.  Foundry requires certain things for its recipes to function and the default mechanics to function.  Thermal Foundation is not a burden whatsoever, so it's not an issue.  Besides, I can't think of another mod providing everything ThF does off the top of my head.
