### ISSUE TITLE
Broken orestack bracket handler?

### ISSUE THREAD

**Issue by Matryoshika** [Shadows-of-Fire/Foundry#16]
Foundry: 3.1.1.0
Forge: 14.23.2.2615
I'm reducing the output of some ores, from 1 ingot down to just 1 nugget, however, I'm running into a wall when trying to bring that over to Foundry.
`mods.foundry.Melting.removeRecipe(<orestack:oreIron> * 1);`, and several other variations like using CrT's own ore-brackethandler, with and without size etc, all return `a method available 
but none matches the parameters (ZenTypeNative: crafttweaker.item.IIngredient) removeRecipe(ZenTypeNative: crafttweaker.item.IItemStack)`

**Comment by Shadows-of-Fire** [comment]
Foundry's removal method for this only takes an IItemStack, not an IIngredient.  The recipes aren't per stack by default, so remove(<minecraft:iron_ore>) will remove oreIron.
