### ISSUE TITLE
CraftTweaker script interface change

### ISSUE THREAD

**Issue by Efimero** [Shadows-of-Fire/Foundry#19]
from 1.1.0 to 1.1.1, a script that works, for the casting table, stops working
in 1.1.0 it creates the Casting recipe no problem
in 1.1.1 Casting.addRecipe() says it's getting a null when it is not, it is exactly the same script, the only change is the version of Foundry I use
Casting.addRecipe() is the only one I've seen erroring so far; addMold() works

**Comment by Shadows-of-Fire** [comment]
Provide the script.  The changes would not cause foundry ro recieve a false null.

**Comment by Efimero** [comment]
this is the only line erroring, and again, when downgrading foundry to 1.1.0 it works fine, but upgrading breaks it without changing anything in the script

https://gist.github.com/Efimero/e8257c60942809666526360353fdb24b#file-custom_recipes_2-zs-L271

**Comment by Shadows-of-Fire** [comment]
Alright, yeah, so its not a *false* null, but I changed a method somewhere else and the `@Optional IIngredient extra` is null if not present, it then gets passed to a method that should not receive null anymore.
