### ISSUE TITLE
RF value of induction heater goes negative 

### ISSUE THREAD

**Issue by superfluke** [Shadows-of-Fire/Foundry#2]
When powering the induction heater with various creative cube, the rf shown in the one probe is negative and the block does not provide heat if a crucible is set on top.
Immersive eng creative power: negative rf
Mek creative energy cube: negative rf
Draconic creative rf source: nefative rf
Extra utils creative energy: works fine

![2017-11-12_15 28 27](https://user-images.githubusercontent.com/20022336/32703064-8f71dbc2-c7be-11e7-94db-ef8d084f1fc4.png)
Forge version 14.23.0.2522
Foundry 1.12.2-3.0.0.1.jar

**Comment by Shadows-of-Fire** [comment]
I uh, I'm not entirely sure what's going on with these.  They work properly with non-creative energy sources, (and they also work with pipes from creative energy sources), so it's not a huge issue that deserves immediate attention.
