### ISSUE TITLE
crash with EnderIO

### ISSUE THREAD

**Issue by 0Navis0** [Shadows-of-Fire/Foundry#22]
Foundry crashes with the EnderIO on 1.12. https://pastebin.com/BPinEvMW

**Comment by Shadows-of-Fire** [comment]
Will fix as soon as EnderIO 5 is available on a maven repo

**Comment by Shadows-of-Fire** [comment]
https://www.dropbox.com/s/2qve4cmy8iaqlkj/Foundry-1.12.2-3.1.2.0.jar?dl=0
This dev build shouldn't crash, but it's not tested at all.

**Comment by 0Navis0** [comment]
For me it works all fine ;)
