### ISSUE TITLE
Thermal Expansion and TConstruct fluids should be used instead of Foundry fluids

### ISSUE THREAD

**Issue by 0Navis0** [Shadows-of-Fire/Foundry#24]
I would suggest to remove Foundry fluids now it's not more a dependency of Substratum and works as a Thermal Expansion addon, Thermal Expansion and TConstruct fluids should be used intead as Embers does. Otherwise it makes fluid duplication, and Foundry fluids can't be used with TConstrust fluids for alloys.

**Comment by Shadows-of-Fire** [comment]
This is a significantly breaking change and it would not happen in the lifespan of 1.12 at least, it might not at all.  I don't really *want* to go switch over to the TiC fluids anyway, and I won't invalidate every existing world by making that change now.
