### ISSUE TITLE
Buckets

### ISSUE THREAD

**Issue by scalda** [Shadows-of-Fire/Foundry#25]
Hi is there a way to register all your liquids to forge so we can get buckets as we are planning on using this in replacement for tinkers, as we are using minimoos but without your liquids in the forge buckets they don't get added to mini moos config for them to be usable there.

any help would be great

**Comment by Shadows-of-Fire** [comment]
They should work in the buckets already (all fluids go through forge anyway) but maybe the universal bucket isnt getting turned on properly.
And ignore the close/reopen there, wrong button.

**Comment by scalda** [comment]
Yeah there is no bucket types for the liquids for your mod

Edit: Just tested, i can't pick up a source block of liquid with a bucket or from a tank

**Comment by scalda** [comment]
Thankyou for the fix
