### ISSUE TITLE
Can't make brass casings with no mod that adds zinc

### ISSUE THREAD

**Issue by CplPibald** [Shadows-of-Fire/Foundry#26]
Foundry 1.12.2-3.1.2.0
Thermal Foundation 2.3.11.8
CoFH Core 4.3.11.6

Tried to make bullets for a Foundry revolver, but I had a problem creating the round and shell casings, which must be cast from liquid brass.  According to JEI, liquid brass can made by alloying copper and zinc, but ThermalFoundation does not have zinc or any other type of brass.  **Foundry itself adds *liquid* brass and zinc, but there are no ingots or ores for either metal.**

**Suggestion**: when brass and zinc aren't available in a modpack, allow casings to be cast or made from available materials (eg: bronze, invar, or anything from Thermal Foundation).  Alternatively, allow alloying recipes for these metals to be set in the config so that modpack creators can make this work with available metals.

For now, the workaround is to add a recipe to create casings directly using minetweaker.  I would prefer using the excellent casting mechanics in Foundry though.

**Comment by Shadows-of-Fire** [comment]
You can edit the casting recipes via minetweaker, but yeah.  If zinc isnt present, it should probably try something else.  That would explain where the untraceable errors for invalid blockZinc matches were coming from...

**Comment by Shadows-of-Fire** [comment]
I think the best solution here is going to be to replace zinc in those recipes with aluminum.  Problem with that is that it doesn't spawn by default.  I might be able to just add that to the default cofh/world configs though.

**Comment by CplPibald** [comment]
That could also work for mod compat with TiCon which already has an alloying recipe of copper + aluminum -> brass.
