### ISSUE TITLE
Help with broken script

### ISSUE THREAD

**Issue by davqvist** [Shadows-of-Fire/Foundry#29]
So I had a script that worked fine, now I updated my pack and suddenly I get 2 "WARNING: Casting recipe not found" errors. I haven't changed any script, I haven't updated Foundry or Crafttweaker, I haven't updated Forge, so I am clueless.

Here is the crafttweaker.log https://hastebin.com/ukiharaqaw.md
Here is the Foundry.zs https://hastebin.com/yodohizabi.xml

One of the lines not working is `mods.foundry.Casting.removeRecipe(<liquid:liquidglass> * 1000, <foundry:mold:4>);` but it was working before. So help would be appreciated.

**Comment by pyure** [comment]
If you do (I think) /ct liquids, is your liquid in that list? (liquidglass).  Case sensitivity is crucial.  Even if you didn't update the involved mods, its possible the liquid in question came from a mod which did update.

Another thing: did you change the config'd fluid amount for ingots?  A lot of people are tweaking it from 108 to 144.  Not sure if it would have an impact, but figured I'd raise the possibility.

**Comment by Shadows-of-Fire** [comment]
This was fixed by 9a60d16
