### ISSUE TITLE
Request: Ability to remove all recipes from a machine.

### ISSUE THREAD

**Issue by pyure** [Shadows-of-Fire/Foundry#30]
Possible example: 
`mods.foundry.Casting.removeAll()`

**Comment by pyure** [comment]
Can confirm fixed by https://github.com/Shadows-of-Fire/Foundry/commit/b17bb57651f87090f1ae869584b4c2d60d11ec9f

**Comment by pyure** [comment]
@Shadows-of-Fire did you apply this to mods.foundry.Casting?  I couldn't find it in the commit, and I'm getting an error when I do mods.foundry.Casting.clear();

It works fine for "Melting".

**Comment by Shadows-of-Fire** [comment]
Castinf#clearRecipes/Casting#clearMolds

**Comment by pyure** [comment]
I don't understand your reply, sorry :(

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Foundry/blob/1.12.2/src/main/java/exter/foundry/integration/minetweaker/MTCastingHandler.java#L158
