### ISSUE TITLE
Wrong Default values for TF Boots

### ISSUE THREAD

**Issue by WindFox** [Shadows-of-Fire/Foundry#37]
I just noticed that to cast boots from Thermal Foundation, you would spend 5 ingots instead of 4.
And yet, vanilla Iron and golden boots are correct.

Yes, one can fix this in crafttweaker, but I just wanted to let you know.

**Comment by WindFox** [comment]
Also, Aluminum and Constantan armors have no default casting recipes.

Edit: I seriously cannot type today.

**Comment by Shadows-of-Fire** [comment]
Oh, yeah, boots were using the helm value for some reason.  I'll see about the aluminum and constantan armor stuff, matching ingot->armor is a sensitive process since there's no good way to go about doing it.

**Comment by WindFox** [comment]
I believe it's due to different wording/spelling for the liquid vs metal.
Aluminum vs Aluminium and Constantan and Cupernickel.

...and it's not just the armors. Tools too.
Just a theory.

**Comment by Shadows-of-Fire** [comment]
Yeah I'm special casing those now, gets annoying when things have two different names that aren't the same across most mods
