### ISSUE TITLE
[Request] Hardcore options work the other way

### ISSUE THREAD

**Issue by WindFox** [Shadows-of-Fire/Foundry#38]
So, I was messing with the hardcore options and I noticed that while I can disable the 9 to 1 compression recipes, the 1 to 9 decompression however still exists.

Any chance this can be fixed?

**Comment by Shadows-of-Fire** [comment]
You could probably accomplish it with CraftTweaker, the hardcore options are something I would like to remove anyway.

Maybe I'll rewrite them instead of delete them, but nothing anytime soon.

**Comment by WindFox** [comment]
Honestly, I kinda like them. Making people actually melt their metals into other forms instead of just using their hands to either squish metal into larger forms or rip them apart into smaller forms...

....holy carp.... Steve and Alex are STRONG!
