### ISSUE TITLE
Configurable Gun Skeletons

### ISSUE THREAD

**Issue by pyure** [Shadows-of-Fire/Foundry#43]
Hey Shadows,

I'm just gonna add my voice to the list.  Do you mind making these configurable?

**Comment by Shadows-of-Fire** [comment]
Duplicate of #42
But I'll see what I can do about it, i suppose.  I was trying not to do anything w/ foundry because I was rewriting the internals, but that looks like its going to take ages.

**Comment by pyure** [comment]
It wouldn't be the first time you've gone way out of your way to do me a big favour :p 

(Thanks as always)
