### ISSUE TITLE
[Crash] Can't use CraftTweaker on regular crafting recipes?

### ISSUE THREAD

**Issue by vizthex123** [Shadows-of-Fire/Foundry#48]
So I'm trying to make the Refractory Clay use the Ore Dictionary, but it's not working. It just crashes my game.
Disabling the script makes it work fine though.

Script & Crash attached.

[crash-2019-11-23_12.22.46-client.txt](https://github.com/Shadows-of-Fire/Foundry/files/3882796/crash-2019-11-23_12.22.46-client.txt)

[foundry.txt](https://github.com/Shadows-of-Fire/Foundry/files/3882797/foundry.txt)

**Comment by Shadows-of-Fire** [comment]
This is an error in your script.  You have a comment that begins with `/ /` instead of `//` so it is not detected as a comment, but an erroneous line in the file.
