### ISSUE TITLE
Invalid OreMatcher (blockCharcoal)

### ISSUE THREAD

**Issue by darkphan** [Shadows-of-Fire/Foundry#7]
Version: Foundry-1.12.2-3.1.0.2

Game crashes with "Invalid OreMatcher (blockCharcoal) when launching

Crash log: https://pste.me/#/n9bPw

**Comment by Shadows-of-Fire** [comment]
I realize I'm an idiot, I have Mekanism in my dev environment, which was providing a charcoal block.
