### ISSUE TITLE
Invalid OreMatcher (dustZinc)

### ISSUE THREAD

**Issue by darkphan** [Shadows-of-Fire/Foundry#8]
Version: Foundry-1.12.2-3.1.0.2

Game crashes with "Invalid OreMatcher (dustZinc)" when launching

Crash log: https://pste.me/#/P23rD

I did try  removing zinc from the "remove_ingots_from_furnace.keep" setting with the same results

**Comment by Shadows-of-Fire** [comment]
Huh.  You have a mod providing a zinc ingot and not a zinc dust?  Weird, but will be fixed soon

**Comment by Shadows-of-Fire** [comment]
Check if the issue persists with 3.1.0.4 when it's approved.

**Comment by darkphan** [comment]
Yeah, I think Silent Gems Extra Parts adds zinc, will verify that its working when its approved.
