### ISSUE TITLE
Machines cannot be powered by Thermal Expansion

### ISSUE THREAD

**Issue by Akitori** [Shadows-of-Fire/Foundry#9]
Trying to power any machine using thermal foundation dynamos/energycells/whatever just causes the game to lag out. 

Forge version: 1.12.2 2555
Foundry: 3.1.0.4
placebo:1.1.2

**Comment by Shadows-of-Fire** [comment]
I cannot reproduce this whatsoever.  Powering foundry machines from TE stuff works just fine.

**Comment by Akitori** [comment]
turns out its a issue with a mod called "particle spreader" great. Thanks anyhow!

**Comment by Akitori** [comment]
rather its library, limelib
